### ISSUE TITLE
Notifications reminders 

### ISSUE THREAD

**Issue by Myrfion** [Myrfion/sprowt-mobile#60]
# Summary:
Have a daily notification at a certain time  that yes user sets and that notification would lead to specific post, and have certain title and body. The data for notification would come from firebase and if would it have a record in following form
```
ScheduledNotification{
  title: string
  body: string
  postID: string
}
```

Need to add the form to put these notifications on admin that will save them on the firebase. 

## Banner specifications 
- The view of the banner comes from figma, the design that Anna did 
- Banner has 4 times, title, body text, dismiss button and set reminder button
- The title and body text should be different each time we show it. Different copies are gonna be stored locally and if we show all available copies we just go back to the first one. 
- If the user presses on dismiss button we set a timeout on showing it and how it on the first visit after 7 days 
- If user presses on "set reminder" button he is redirected to the set reminder screen. 
- If he doesn't set the reminder after going to set reminder screen from banner we do how with setting interval for 1 day

## Create reminder screen specifications 
- When user just goes to create first notification he has only field to enter time and have "set daily notification" button which creates notification on click and then redirect him to the homepage with showing success alert that his notifications were set up
- When user want to edit notifications he goes to daily reminders screen and he should have disable/enable switch, time input with prepopulated time value that they selected before and if he changes something "save changes" button goes green and he should be able to press it and update reminder (refer to the figma design)
- If user didn't provide notification permissions we should show him instructions how to enable them for different platform with button that gonna redirect him to settings 

## Expected behavior:
1. Be able to add/edit/delete list of possible daily notifications in admin
2. From the user perspective: be able to setup daily notification at certain time, 
3. For the banner behaviour refer to Banner Specifications section
4. For the reminder screen specification refer to Create reminder screen specifications section

#### Milestones
- [x] Banner view and business logic with setting interval for certain time depending on user's action - 1.5 days
- [ ] New Onboarding step that refers to daily notifications - 0.5 day
- [ ] Admin logic on creating and managing possible notifications and storing them in the firebase  - 1.5 days
- [x] Create a notification screen (with views according to figma) - 1 day
- [ ] App logic of creating scheduled notifications - 5 days
- [ ] Handling disabled notifications permissions - 0.5 day
