### ISSUE TITLE
Feature: Ability to onboard organizations by mass uploading CSV doc

### ISSUE THREAD

**Issue by Myrfion** [Myrfion/sprowt-mobile#61]
# Summary:
We should be able to add organizations to our list of organizations. For each organization, we should be able to upload the list of users from the csv file. It going to include the name of the user and his email. When uploaded, all users should get an email with an invitation and link to download the app. Then user signs up with that email and in the application, he gonna see the logo of his organization and they gonna have a full access to all features (so pretty much much like premium users) 

#### Tasks
- [ ] Managing of organization in admin (creating it, uploading CSV with a list of people, uploading logo) 
- [ ] Script that gonna send people invitation emails when CSV is uploaded 
- [ ] Showing the company's logo in an application beside our logo
- [ ] Providing users who are part of an organization with the same access as premium users have
